/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Archivos;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Javier
 */
public class gameOver extends javax.swing.JFrame {

    /**
     * Creates new form gameOver
     */
    public gameOver() {
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(lbAlgas, "src/Imagenes/algas-marinas.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lbAlgas2, "src/Imagenes/algas-marinas2.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lbFondo, "src/Imagenes/fondoOver.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lbTortuga, "src/Imagenes/tortuga-marina.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lbCorales, "src/Imagenes/Conchita.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lbConchi, "src/Imagenes/conhiman.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lbCalamar, "src/Imagenes/triste.png");
        
        try {
            String consulta = "select top 1 Nombre from Resultados ORDER BY ID DESC";
            
            PreparedStatement n = conexion.getConexion().prepareStatement(consulta);
            
            java.sql.ResultSet resultado = n.executeQuery();
            
            if (resultado.next()) 
            {
                 String nombre = resultado.getString("Nombre");
                 lbNombre.setText(nombre);
            } 
            else 
            {
                 lbNombre.setText("Usuario no encontrado");
            }
        } 
        catch (SQLException ex) 
        {
            
         JOptionPane.showMessageDialog(this, ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        lbNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbCalamar = new javax.swing.JLabel();
        lbConchi = new javax.swing.JLabel();
        lbTortuga = new javax.swing.JLabel();
        lbCorales = new javax.swing.JLabel();
        lbAlgas = new javax.swing.JLabel();
        lbAlgas2 = new javax.swing.JLabel();
        lbFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelFondo.setBackground(new java.awt.Color(184, 182, 244));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNombre.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(255, 255, 255));
        lbNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNombre.setText("  jLabel2");
        lbNombre.setAlignmentX(0.5F);
        lbNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelFondo.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 260, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Perdiste");
        panelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        lbCalamar.setText("jLabel1");
        panelFondo.add(lbCalamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 290, 260));
        panelFondo.add(lbConchi, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 390, 70, 30));

        lbTortuga.setText("jLabel1");
        panelFondo.add(lbTortuga, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 140, 70));
        panelFondo.add(lbCorales, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 350, 100, 80));
        panelFondo.add(lbAlgas, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 230, 270, 200));

        lbAlgas2.setText("jLabel1");
        panelFondo.add(lbAlgas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 290, 200));

        lbFondo.setText("jLabel1");
        panelFondo.add(lbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameOver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbAlgas;
    private javax.swing.JLabel lbAlgas2;
    private javax.swing.JLabel lbCalamar;
    private javax.swing.JLabel lbConchi;
    private javax.swing.JLabel lbCorales;
    private javax.swing.JLabel lbFondo;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbTortuga;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables
}
