/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Archivos;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Javier
 */
public class win extends javax.swing.JFrame {

    /**
     * Creates new form win
     */
    public win() {
        initComponents();
        rsscalelabel.RSScaleLabel.setScaleLabel(lbPulpow, "src/Imagenes/feliz.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lbTortu, "src/Imagenes/tortuga-marina.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lbConci, "src/Imagenes/Conchita.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lbAlgasw, "src/imagenes/Algas 2.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lbConcha, "src/Imagenes/conhiman.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lbAlgaw, "src/imagenes/algas-marinas 2.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lbFondow, "src/Imagenes/fondoOver.png");
        
                try {
            String consulta = "select top 1 Nombre from Resultados ORDER BY ID DESC";
            
            PreparedStatement n = conexion.getConexion().prepareStatement(consulta);
            
            java.sql.ResultSet resultado = n.executeQuery();
            
            if (resultado.next()) 
            {
                 String nombre = resultado.getString("Nombre");
                 lbNombre.setText(nombre);
            } 
            else 
            {
                 lbNombre.setText("Usuario no encontrado");
            }
        } 
        catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbConcha = new javax.swing.JLabel();
        lbConci = new javax.swing.JLabel();
        lbTortu = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbPulpow = new javax.swing.JLabel();
        lbAlgasw = new javax.swing.JLabel();
        lbAlgaw = new javax.swing.JLabel();
        lbFondow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(184, 182, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ganaste");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        lbConcha.setText("jLabel2");
        jPanel1.add(lbConcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 90, 40));

        lbConci.setText("jLabel2");
        jPanel1.add(lbConci, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 366, 100, 60));

        lbTortu.setText("jLabel2");
        jPanel1.add(lbTortu, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 336, 120, 90));

        lbNombre.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(255, 255, 255));
        lbNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNombre.setText("  jLabel2");
        lbNombre.setAlignmentX(0.5F);
        lbNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 260, -1));

        lbPulpow.setText("jLabel1");
        jPanel1.add(lbPulpow, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 260, 240));

        lbAlgasw.setText("jLabel1");
        jPanel1.add(lbAlgasw, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 280, 190));

        lbAlgaw.setText("jLabel1");
        jPanel1.add(lbAlgaw, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 260, 190));

        lbFondow.setText("jLabel1");
        jPanel1.add(lbFondow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new win().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAlgasw;
    private javax.swing.JLabel lbAlgaw;
    private javax.swing.JLabel lbConcha;
    private javax.swing.JLabel lbConci;
    private javax.swing.JLabel lbFondow;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPulpow;
    private javax.swing.JLabel lbTortu;
    // End of variables declaration//GEN-END:variables
}
